### ISSUE TITLE
tasmota_irhvac:set_swingv is not working - throwing Unknown error on Automation scene

### ISSUE THREAD

**Issue by rvignesh123** [hristo-atanasov/Tasmota-IRHVAC#115]
![Screenshot 2023-06-08 at 7 44 02 PM](https://github.com/hristo-atanasov/Tasmota-IRHVAC/assets/5195564/a8a9ca14-0fe8-48d8-8f2c-5b1fcdb60bc5)

I tried looking at the logs:

![Screenshot 2023-06-08 at 7 33 55 PM](https://github.com/hristo-atanasov/Tasmota-IRHVAC/assets/5195564/0e57b0b0-1aa3-4239-96b7-2c086c9fbe9a)

Please help me to fix this.

**Comment by nao-pon** [comment]
@rvignesh123  I've tried running the automation shown below and nothing happened.
Is this component of yours up to date?

```yaml
alias: test
description: ""
trigger:
  - platform: time
    at: "23:39:00"
condition: []
action:
  - service: tasmota_irhvac.set_swingv
    data:
      swingv: auto
    target:
      entity_id: climate.to_debug
mode: single
```
