### ISSUE TITLE
Tasmota receiving unknown commands on HA 2024.5.3

### ISSUE THREAD

**Issue by sjaks** [hristo-atanasov/Tasmota-IRHVAC#138]
Tasmota-IRHAC used to work well last summer when I had HA 2023.5 installed. Now that a year has passed and I'm on 2024.5.3, I cannot control my AC unit at all. It seems the Tasmota device (ESP32 running tasmota-ir v. 13.0.0) is receiving the following MQTT messages for each action I do with the hvac entity:

```
17:36:55.712 MQT: stat/tasmota_hvac/RESULT = {"Command":"Unknown"}
```

I just downloaded the latest version of Tasmota-IRHVAC (v2024.4.0). The config I haven't touched but worked last year:

```
climate:
  - platform: tasmota_irhvac
    name: "IR HVAC"
    command_topic: "cmnd/tasmota_hvac/irhvac"
    state_topic: "tele/tasmota_hvac/RESULT"
    temperature_sensor: sensor.living_room_temperature
    humidity_sensor: sensor.living_room_humidity
    vendor: "TROTEC_3550"
    mqtt_delay: 0.0
    min_temp: 16
    max_temp: 26
    target_temp: 20
    supported_modes:
      - "cool"
      - "dry"
      - "fan_only"
      - "off"
    supported_fan_speeds:
      - "medium"
      - "min"
      - "max"
    supported_swing_list:
      - "off"
      - "vertical"
    hvac_model: "-1"
    celsius_mode: "On"
    keep_mode_when_off: True
    ignore_off_temp: False
```
