### ISSUE TITLE
Can't find entity

### ISSUE THREAD

**Issue by Jasonlynet** [hristo-atanasov/Tasmota-IRHVAC#146]
Based on your configuration instruction, I can't find entity.....
Everything goes fine with HA. 
Check completely right. 

Could u help me to check the config file?

Looking forward to your reply.

System version:
Home Assistant Core 2024.6.3

Config detail as follow:
```yaml
climate:
  - platform: tasmota_irhvac
    name: "FF"
    command_topic: "cmnd/tasmota_1883A2/irhvac"
    state_topic: "tele/tasmota_1883A2/RESULT"
    vendor: "Gree"
    mqtt_delay: 0.0 #optional - default 0 int or 0.0 float value in [sec].
    min_temp: 16 #optional - default 16 int value
    max_temp: 32 #optional - default 32 int value
    target_temp: 26 #optional - default 26 int value
    initial_operation_mode: "off" # optional - default "off" string value (one of the "supported_modes")
    away_temp: 24 #optional - default 24 int value
    precision: 1 #optional - default 1 int or float value. Can be set to 1, 0.5 or 0.1
    supported_modes:
      - "heat"
      - "cool"
      - "dry"
      - "fan_only" # Use "fan_only" even if Tasmota shows "Mode":"Fan"
      - "auto"
      - "off" #Turns the AC off - Should be in quotes
    supported_fan_speeds:
      - "medium"
      - "min"
      - "max"
      - "auto"
    supported_swing_list:
      - "off"
    default_quiet_mode: "Off" #optional - default "Off" string value
    default_turbo_mode: "Off" #optional - default "Off" string value
    default_econo_mode: "Off" #optional - default "Off" string value
    hvac_model: "1" #optional - default "1" string value
    celsius_mode: "On" #optional - default "On" string value
    default_light_mode: "Off" #optional - default "Off" string value
    default_filter_mode: "Off" #optional - default "Off" string value
    default_clean_mode: "Off" #optional - default "Off" string value
    default_beep_mode: "Off" #optional - default "Off" string value
    default_sleep_mode: "-1" #optional - default "-1" string value
    default_swingv: "high" #optional - default "" string value
    default_swingh: "left" #optional - default "" string value 
    keep_mode_when_off: True #optional - default False boolean value : Must be True for MITSUBISHI_AC, ECOCLIM, etc.
    toggle_list: #optional - default []
```
