### ISSUE TITLE
Reboot Shows climate as offline

### ISSUE THREAD

**Issue by duczz** [hristo-atanasov/Tasmota-IRHVAC#152]
When i have a active climate, after a homeassistent reboot the climate shows this one as offline but it is already activ.
I think this is since a few weeks, Integration problem or homeassistent problem?

Edit: Actuall homeassistent and actuall Integration version

**Comment by hristo-atanasov** [comment]
What is that part with the "Edit"?

**Comment by duczz** [comment]
That you know im everywhere up2date

**Comment by duczz** [comment]
Code:
```
#Büro
- platform: tasmota_irhvac
  name: "Büro Klimaanlage"
  unique_id: "Buero Klimaanlage"
  command_topic: "cmnd/Buero_Klimaanlage/irhvac"
  # Pick one of the following:
  # State is updated when the tasmota device receives an IR signal (includes own transmission and original remote)
  # useful when a normal remote is in use alongside the tasmota device, may be less reliable than the second option.
  #state_topic: "tele/Buero_Klimaanlage/RESULT"
  # State is updated when the tasmota device completes IR transmission, should be pretty reliable.
  #state_topic: "stat/your_tasmota_device/RESULT"
  # Optional second state topic, This option allows you to subscribe to both "tele" and "stat" messages.
  #state_topic_2: "stat/your_tasmota_device/RESULT"
  # Uncomment if your 'available topic' of Tasmota IR device are different (if device in HA is disabled)
  #availability_topic: "tele/your_tasmota_device/LWT"
  temperature_sensor: sensor.wohnzimmer_temperatursensor_snzb_02_temperature
  humidity_sensor: sensor.wohnzimmer_temperatursensor_snzb_02_humidity #optional - default None
  #power_sensor: binaly_sensor.kitchen_ac_power #optional - default None
  vendor: "PANASONIC_AC"
  min_temp: 16 #optional - default 16 int value
  max_temp: 30 #optional - default 32 int value
  target_temp: 26 #optional - default 26 int value
  initial_operation_mode: "off" # optional - default "off" string value (one of the "supported_modes")
  #away_temp: 24 #optional - default 24 int value (preset_modes)
  precision: 1 #optional - default 1 int or float value. Can be set to 1, 0.5 or 0.1
  supported_modes:
    - "auto"
    - "heat"
    - "cool"
    - "dry"
    #- "fan_only" # Use "fan_only" even if Tasmota shows "Mode":"Fan"
    - "off" #Turns the AC off - Should be in quotes
    # Some devices have "auto" and "fan_only" switched. If the following two lines are uncommented, "auto" and "fan" shoud be commented out
    #- "auto_fan_only" #if remote shows fan but tasmota says auto
    #- "fan_only_auto" #if remote shows auto but tasmota says fan
  supported_fan_speeds:
    # Some devices say max,but it is high, and auto which is max. If you uncomment the following two, you have to comment high and max
    # - "auto_max" #woud become max
    # - "max_high" #would become high
    #- "on"
    #- "off"
    - "auto"
    - "min"
    - "low"
    - "medium"
    - "high"
    - "max"
  supported_swing_list:
    - "off"
    - "vertical" #up to down
    - "horizontal" # Left to right
    #- "both"
  default_quiet_mode: "Off" #Quiet und Turbo sind in der Firmware vertauscht | optional - default "Off" string value
  default_turbo_mode: "On" #Quiet und Turbo sind in der Firmware vertauscht | optional - default "Off" string value
  default_econo_mode: "Off" #optional - default "Off" string value
  hvac_model: "3" #optional - default "1" string value
  celsius_mode: "On" #optional - default "On" string value
  default_light_mode: "Off" #optional - default "Off" string value
  default_filter_mode: "Off" #optional - default "Off" string value
  default_clean_mode: "Off" #optional - default "Off" string value
  default_beep_mode: "Off" #optional - default "Off" string value
  default_sleep_mode: "-1" #optional - default "-1" string value
  default_swingv: "high" #optional - default "" string value
  default_swingh: "middle" #optional - default "" string value
  keep_mode_when_off: false #optional - default False boolean value : Must be True for MITSUBISHI_AC, ECOCLIM, etc.

```
