### ISSUE TITLE
Two AC's on two different D1Mini's

### ISSUE THREAD

**Issue by mircsicz** [hristo-atanasov/Tasmota-IRHVAC#160]
First of all let me share my gratitude! I've been fighting with ESPHome on and off for a few month... On Saturday I had some first contact with your Project and gosh what a blessing!!!

I'm on 14.3.0 tasmota_ir.bin and about to build my own tasmota_ircustom.bin to integrate I2C for my various sensors...

I've so far added our Livingroom AC (LG2) and it worked totally as expected. Now that I've added our Bedroom (MIRAGE) I see an issue:
The Commands for the bedroom are being sent in the livingroom...

This is my configuration.yml:
`climate: !include climate.yml`

and this is the content of climate.yml:
```
- platform: tasmota_irhvac
  name: "Livingroom"
  command_topic: "cmnd/tasmota_4F0C85/irhvac"
  state_topic: "tele/tasmota_4F0C85/RESULT"
  state_topic_2: "stat/tasmota_4F0C85/RESULT"
  temperature_sensor: sensor.kitchen_temperature
  humidity_sensor: sensor.kitchen_humidity # optional - default None
  vendor: "LG2"
  mqtt_delay: 0.0 # optional - default 0 int or 0.0 float value in [sec].
  min_temp: 23 # optional - default 16 int value
  max_temp: 29 # optional - default 32 int value
  target_temp: 26 # optional - default 26 int value
  initial_operation_mode: "off" # optional - default "off" string value (one of the "supported_modes")
  away_temp: 27 # optional - default 24 int value
  precision: 1 # optional - default 1 int or float value. Can be set to 1, 0.5 or 0.1
  supported_modes:
   - "heat"
   - "cool"
   - "dry"
   - "fan_only" # Use "fan_only" even if Tasmota shows "Mode":"Fan"
   - "auto"
   - "off" #Turns the AC off - Should be in quotes
  supported_fan_speeds:
   # Some devices say max,but it is high, and auto which is max
   # If you uncomment the following two, you have to comment high and max
   # - "auto_max" #woud become max
   # - "max_high" #would become high
   # - "on"
   # - "off"
   # - "low"
   - "medium"
   - "high"
   #- "middle"
   #- "focus"
   #- "diffuse"
   - "min"
   - "max"
   #- "auto"
  supported_swing_list:
   - "off"
   - "vertical" #up to down
  default_quiet_mode: "Off" #optional - default "Off" string value
  default_turbo_mode: "Off" #optional - default "Off" string value
  default_econo_mode: "Off" #optional - default "Off" string value
  hvac_model: "-1" #optional - default "1" string value
  celsius_mode: "On" #optional - default "On" string value
  default_light_mode: "Off" #optional - default "Off" string value
  default_filter_mode: "Off" #optional - default "Off" string value
  default_clean_mode: "Off" #optional - default "Off" string value
  default_beep_mode: "Off" #optional - default "Off" string value
  default_sleep_mode: "-1" #optional - default "-1" string value
  default_swingv: "high" #optional - default "" string value
  default_swingh: "left" #optional - default "" string value 
  keep_mode_when_off: True #optional - default False boolean value : Must be True for MITSUBISHI_AC, ECOCLIM, etc.
  ignore_off_temp: False #optional - default False boolean value
- platform: tasmota_irhvac
  name: "Bedroom"
  command_topic: "cmnd/tasmota_4F0836/irhvac"
  state_topic: "tele/tasmota_4F0836/RESULT"
  state_topic_2: "stat/tasmota_4F0836/RESULT"
  temperature_sensor: sensor.kitchen_temperature
  humidity_sensor: sensor.kitchen_humidity # optional - default None
  vendor: "MIRAGE"
  mqtt_delay: 0.0 # optional - default 0 int or 0.0 float value in [sec].
  min_temp: 23 # optional - default 16 int value
  max_temp: 29 # optional - default 32 int value
  target_temp: 26 # optional - default 26 int value
  initial_operation_mode: "off" # optional - default "off" string value (one of the "supported_modes")
  away_temp: 27 # optional - default 24 int value
  precision: 1 # optional - default 1 int or float value. Can be set to 1, 0.5 or 0.1
  supported_modes:
   - "heat"
   - "cool"
   - "dry"
   - "fan_only" # Use "fan_only" even if Tasmota shows "Mode":"Fan"
   - "auto"
   - "off" #Turns the AC off - Should be in quotes
  supported_fan_speeds:
   # Some devices say max,but it is high, and auto which is max
   # If you uncomment the following two, you have to comment high and max
   # - "auto_max" #woud become max
   # - "max_high" #would become high
   # - "on"
   # - "off"
   # - "low"
   - "medium"
   - "high"
   #- "middle"
   #- "focus"
   #- "diffuse"
   - "min"
   - "max"
   #- "auto"
  supported_swing_list:
   - "off"
   - "vertical" #up to down
  default_quiet_mode: "Off" #optional - default "Off" string value
  default_turbo_mode: "Off" #optional - default "Off" string value
  default_econo_mode: "Off" #optional - default "Off" string value
  hvac_model: "-1" #optional - default "1" string value
  celsius_mode: "On" #optional - default "On" string value
  default_light_mode: "Off" #optional - default "Off" string value
  default_filter_mode: "Off" #optional - default "Off" string value
  default_clean_mode: "Off" #optional - default "Off" string value
  default_beep_mode: "Off" #optional - default "Off" string value
  default_sleep_mode: "-1" #optional - default "-1" string value
  default_swingv: "high" #optional - default "" string value
  default_swingh: "left" #optional - default "" string value 
  keep_mode_when_off: True #optional - default False boolean value : Must be True for MITSUBISHI_AC, ECOCLIM, etc.
```

as command- and state_topic's are different I don't know where to look for the problem... 

Hoping for hints ;-)

**Comment by mircsicz** [comment]
After stwo or three more HA restarts the problem disappeared!

I did restart because I did check a bit more detailed on supported modes:
```
- platform: tasmota_irhvac
  name: "Livingroom"
  command_topic: "cmnd/tasmota_4F0C85/irhvac"
  state_topic: "tele/tasmota_4F0C85/RESULT"
  state_topic_2: "stat/tasmota_4F0C85/RESULT"
  temperature_sensor: sensor.kitchen_temperature
  humidity_sensor: sensor.kitchen_humidity # optional - default None
  vendor: "LG2"
  mqtt_delay: 0.0 # optional - default 0 int or 0.0 float value in [sec].
  min_temp: 23 # optional - default 16 int value
  max_temp: 29 # optional - default 32 int value
  target_temp: 26 # optional - default 26 int value
  initial_operation_mode: "off" # optional - default "off" string value (one of the "supported_modes")
  away_temp: 27 # optional - default 24 int value
  precision: 1 # optional - default 1 int or float value. Can be set to 1, 0.5 or 0.1
  supported_modes:
   - "heat"
   - "cool"
   - "dry"
   - "fan_only" # Use "fan_only" even if Tasmota shows "Mode":"Fan"
   - "auto"
   - "off" #Turns the AC off - Should be in quotes
  supported_fan_speeds:
   - "min"
   - "low"
   - "medium"
   - "high"
   - "max"
   - "auto"
  supported_swing_list:
   - "off"
   - "vertical" #up to down
  default_quiet_mode: "Off" #optional - default "Off" string value
  default_turbo_mode: "Off" #optional - default "Off" string value
  default_econo_mode: "Off" #optional - default "Off" string value
  hvac_model: "-1" #optional - default "1" string value
  default_light_mode: "Off" #optional - default "Off" string value
  default_filter_mode: "Off" #optional - default "Off" string value
  default_clean_mode: "Off" #optional - default "Off" string value
  default_beep_mode: "Off" #optional - default "Off" string value
  default_sleep_mode: "-1" #optional - default "-1" string value
  default_swingv: "high" #optional - default "" string value
  default_swingh: "left" #optional - default "" string value 
  keep_mode_when_off: True #optional - default False boolean value : Must be True for MITSUBISHI_AC, ECOCLIM, etc.
  ignore_off_temp: False #optional - default False boolean value
- platform: tasmota_irhvac
  name: "Bedroom"
  command_topic: "cmnd/tasmota_4F0836/irhvac"
  state_topic: "tele/tasmota_4F0836/RESULT"
  state_topic_2: "stat/tasmota_4F0836/RESULT"
  temperature_sensor: sensor.kitchen_temperature
  humidity_sensor: sensor.kitchen_humidity # optional - default None
  vendor: "MIRAGE"
  mqtt_delay: 0.0 # optional - default 0 int or 0.0 float value in [sec].
  min_temp: 23 # optional - default 16 int value
  max_temp: 29 # optional - default 32 int value
  target_temp: 26 # optional - default 26 int value
  initial_operation_mode: "off" # optional - default "off" string value (one of the "supported_modes")
  away_temp: 27 # optional - default 24 int value
  precision: 1 # optional - default 1 int or float value. Can be set to 1, 0.5 or 0.1
  supported_modes:
   - "heat"
   - "cool"
   - "dry"
   - "fan_only" # Use "fan_only" even if Tasmota shows "Mode":"Fan"
   - "off" #Turns the AC off - Should be in quotes
  supported_fan_speeds:
   - "low"
   - "medium"
   - "high"
   - "auto"
  supported_swing_list:
   - "off"
   - "vertical" #up to down
  default_quiet_mode: "On" #optional - default "Off" string value
  default_turbo_mode: "Off" #optional - default "Off" string value
  default_econo_mode: "Off" #optional - default "Off" string value
  hvac_model: "-1" #optional - default "1" string value
  celsius_mode: "On" #optional - default "On" string value
  default_light_mode: "Off" #optional - default "Off" string value
  default_filter_mode: "Off" #optional - default "Off" string value
  default_clean_mode: "Off" #optional - default "Off" string value
  default_beep_mode: "Off" #optional - default "Off" string value
  default_sleep_mode: "-1" #optional - default "-1" string value
  default_swingv: "high" #optional - default "" string value
  default_swingh: "left" #optional - default "" string value 
  keep_mode_when_off: True #optional - default False boolean value : Must be True for MITSUBISHI_AC, ECOCLIM, etc.
```
