### ISSUE TITLE
Error setting operation to fan_only in irhvac integration

### ISSUE THREAD

**Issue by crackn** [hristo-atanasov/Tasmota-IRHVAC#69]
Hello,
I am using Tasmota IRHVAC for HA v2022.03.0+ with tasmota dev ver 10.0.0.4 (IRremote8266 v2.8.2 lib)
on my LG Air and everything is working fine except that in the integration card, the fan_only option is returning an error.

the error only occurs inside the 3 dots secondary screen, at the main card screen, the fan_only button works ok.

![IMG_0852](https://user-images.githubusercontent.com/81190839/160337258-783a9b66-c90d-49cd-91e3-68995ff54fd1.PNG)

![IMG_0839](https://user-images.githubusercontent.com/81190839/160335933-01ebec5c-e989-4bf0-9f93-c4bf7a2ee315.PNG)

![IMG_0838](https://user-images.githubusercontent.com/81190839/160335955-e1fad904-88e4-489b-8061-735fa715e549.PNG)

here is my integration configuration:

```
platform: tasmota_irhvac
   name: "Ar da Sala"
   command_topic: "cmnd/salaMultisensor/irhvac"
   state_topic: "stat/salaMultisensor/RESULT"
   temperature_sensor: sensor.temperatura_da_sala
   vendor: "LG"
   min_temp: 18 #optional - default 16 int value
   max_temp: 30 #optional - default 32 int value
   target_temp: 25 #optional - default 26 int value
   initial_operation_mode: "off" # optional - default "off" string value (one of the "supported_modes")
   away_temp: 26 #optional - default 24 int value
   precision: 1.0 #optional - default 1 int or float value. Can be set to 1, 0.5 or 0.1
   supported_modes:
     #- "heat"
     - "cool"
     - "dry"
     - "fan_only"
     - "auto"
     - "off" #Turns the AC off - Should be quoted
     # Some devices have "auto" and "fan_only" chaned
     # If following two lines are uncommented, "auto" and "fan" shoud be commented
     #- auto_fan_only #if remote shows fan but tasmota says auto
     #- fan_only_auto #if remote shows auto but tasmota says fan
   supported_fan_speeds:
     # Some devices say max,but it is high, and auto which is max
     # If you uncomment the following two, you have to comment high and max
     # - auto_max #woud become max
     # - max_high #would become high
     #- on
     #- off
     #- "low"
     #- "medium"
     #- "high"
     #- middle
     #- focus
     #- diffuse
     - "max"
     - "medium"
     - "min"
     - "auto"
   supported_swing_list:
     - "off"
     - "vertical" #up to down
    # - "horizontal" # Left to right
    # - "both"
   default_quiet_mode: "Off" #optional - default "Off" string value
   default_turbo_mode: "Off" #optional - default "Off" string value
   default_econo_mode: "Off" #optional - default "Off" string value
   hvac_model: "5" #optional - default "1" string value
   celsius_mode: "On" #optional - default "On" string value
   default_light_mode: "Off" #optional - default "Off" string value
   default_filter_mode: "Off" #optional - default "Off" string value
   default_clean_mode: "Off" #optional - default "Off" string value
   default_beep_mode: "Off" #optional - default "Off" string value
   default_sleep_mode: "-1" #optional - default "-1" string value
```

btw. another minor issue is that the swing mode for LG is a toggle function. if possible, would be great to have the toggle option in place of (Vertical / Off) drop down menu. 

thanks in advance.
