### ISSUE TITLE
Home Assistant switches Midea unit to SC mode

### ISSUE THREAD

**Issue by bkcberry** [hristo-atanasov/Tasmota-IRHVAC#82]
I am on the latest release from here, and HA  2021.12.4. When i try to use HA to change the AC set point or turn it on or off, most of the time it just switches to self clean mode, but sometimes if try it several times it will start working. Config below, any ideas?

```
  - platform: tasmota_irhvac
    name: Playroom AC
    command_topic: "cmnd/playroom/irhvac"
    state_topic: "tele/playroom/RESULT"
    #temperature_sensor: sensor.kitchen_temperature #optional this sensor is used to display current temp on the AC card
    protocol: "MIDEA"
    min_temp: 67 #optional - default 16 int value
    max_temp: 74 #optional - default 32 int value
    #default_clean_mode: "Off"
    target_temp: 72 #optional - default 26 int value
    initial_operation_mode: "off" # optional - default "off" string value
    away_temp: 74 #optional - default 24 int value
    precision: 1.0 #optional - default 1.0 float value
    supported_modes:
      - heat
      - cool
      #- dry
      - fan_only
      - auto
      - "off" #Turns the AC off - Should be quoted and should be always included here
    supported_fan_speeds:
      #- low
      #- max
      #- medium
      # - high
      #- middle
      #- focus
      #- diffuse
      #- min
      - auto
    supported_swing_list:
      - "off"
      - vertical #up to down
      #- horizontal # Left to right - remove if your AC does not support it
      #- both # remove if your AC does not support horizontal
    default_quiet_mode: "Off" #optional - default "Off" string value
    default_turbo_mode: "Off" #optional - default "Off" string value
    default_econo_mode: "Off" #optional - default "Off" string value
    hvac_model: "-1" #optional - default "1" string value
    celsius_mode: "Off" #optional - default "On" string value
    default_light_mode: "Off" #optional - default "Off" string value
    default_filter_mode: "Off" #optional - default "Off" string value
    default_clean_mode: "Off" #optional - default "Off" string value
    default_beep_mode: "Off" #optional - default "Off" string value
    default_sleep_mode: "-1" #optional - default "-1" string value

```
