### ISSUE TITLE
Panasonic AC - SwingV "off" not working

### ISSUE THREAD

**Issue by syfq91** [hristo-atanasov/Tasmota-IRHVAC#85]
My Panasonic AC (model 6) SwingV support 6 different swing modes: `auto/highest/high/middle/low/lowest` but not `off`.
When selecting "off" in home-assistant I can see it issue this command in Tasmota console:

```
13:27:08.720 MQT: stat/irBlaster/RESULT = {"IRHVAC":{"Vendor":"PANASONIC_AC","Model":6,"Mode":"Dry","Power":"On","Celsius":"On","Temp":20,"FanSpeed":"Auto","SwingV":"Off","SwingH":"Off","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1}}
```

This command does not make the swing stop. 
Is it possible to overwrite the "off" with some other available swing mode? Or make it use '`default_swingv` when selecting "off"?

Below are my configuration:

```yaml
climate: 
  - platform: tasmota_irhvac
    name: "BR3 Aircond"
    command_topic: "cmnd/irBlaster/irhvac"
    state_topic: "stat/irBlaster/RESULT"
    temperature_sensor: sensor.br3gateway_htu21_temperature
    humidity_sensor: sensor.br3gateway_htu21_humidity
    power_sensor: binary_sensor.br3sonoffcontact_contact
    vendor: "PANASONIC_AC"
    min_temp: 16
    max_temp: 30
    target_temp: 26
    precision: 1
    supported_modes:
      - "cool"
      - "dry"
      - "auto"
      - "off"
    supported_fan_speeds:
      - "medium"
      - "min"
      - "max"
      - "auto"
    supported_swing_list:
      - "off"
      - "vertical"
    hvac_model: "6" #optional - default "1" string value
    celsius_mode: "On" #optional - default "On" string value
    default_swingv: "middle"
```

**Comment by nao-pon** [comment]
Panasonic AC is in auto mode when swing off. Auto mode is AC automatically controlled, so you need to specify a position to stop the vane completely.

Starting with v2022.08.28, this integration adds a service to control Vane. We can use Input select to control Vane.

## Example

### Input Select Helper
- input_select helper as `input_select.living_ac_swingv`
- options:
```
  - 'off'
  - auto
  - highest
  - high
  - low
  - lowest
```

### Automation

- Target climate as `climate.living_ac`

```yaml
alias: Set AC SwingV
description: ""
trigger:
  - platform: state
    entity_id:
      - climate.living_ac
    attribute: swingv
    id: get
  - platform: state
    entity_id:
      - input_select.living_ac_swingv
    id: set
condition: []
action:
  - if:
      - condition: trigger
        id: set
    then:
      - service: tasmota_irhvac.set_swingv
        data:
          entity_id: climate.living_ac
          swingv: "{{states(trigger.entity_id)}}"
    else:
      - service: input_select.select_option
        data:
          option: "{{state_attr(trigger.entity_id, 'swingv')}}"
        target:
          entity_id: input_select.living_ac_swingv
mode: parallel
max: 2
```
