### ISSUE TITLE
SwingV other modes

### ISSUE THREAD

**Issue by nagyrobi** [hristo-atanasov/Tasmota-IRHVAC#98]
I have `GREE` units, and these have `auto`, `off`, `min`, `max`, `mid` possible modes for `SwingV`, as reported by Tasmota's IrHvac.
Unfortunately here we have it [restricted](https://github.com/hristo-atanasov/Tasmota-IRHVAC/blob/ac9b711cf37de43864b23bb9754995370d6a389a/custom_components/tasmota_irhvac/climate.py#L305) to only `off`, `auto`, `highest`, `high`, `middle`, `low`, `lowest`.

Would be nice if this list would be also configurable so the user could specify the list for SwingV, SwingH corresponding to her/his model. Or maybe it would just be enough to add the missing modes to the list above and the services selector.

**Comment by nagyrobi** [comment]
Here's how I try to use it with a template `select`:

```yaml
template:
  select:
    - name: Hálózsoba klíma legyezés
      unique_id: haloszoba_klima_vswing_uuid
      availability: "{{ states('climate.haloszoba_klima') not in ['unavailable', 'unknown'] }}"
      icon: mdi:swap-vertical-bold
      options: "{{ ['Ki', 'Automatikus', 'Lassú', 'Közepes', 'Gyors'] }}"
      state: >
          {% if is_state_attr('climate.haloszoba_klima', 'fix_swingv', 'off') %}
          Ki
          {%-elif is_state_attr('climate.haloszoba_klima', 'fix_swingv', 'auto') %}
          Automatikus
          {%-elif is_state_attr('climate.haloszoba_klima', 'fix_swingv', 'min') %}
          Lassú
          {%-elif is_state_attr('climate.haloszoba_klima', 'fix_swingv', 'max') %}
          Gyors
          {%-elif is_state_attr('climate.haloszoba_klima', 'fix_swingv', 'mid') %}
          Közepes
          {% endif %}
      select_option:
        - service: tasmota_irhvac.set_swingv
          target:
            entity_id: climate.haloszoba_klima
          data:
            swingv: >
                {% if option == "Automatikus" -%}
                auto
                {% elif option == 'Ki' -%}
                off
                {% elif option == 'Lassú' -%}
                min
                {% elif option == 'Közepes' -%}
                mid
                {% elif option == 'Gyors' -%}
                max
                {% endif -%}

```

**Comment by nao-pon** [comment]
@nagyrobi It seems that I misunderstood that it was normalized by IRremoteESP8266. I'll figure out how to fix this.

**Comment by nagyrobi** [comment]
Also do I understand correctly that `fix_swingv` attribute shows the `SwingV` mode, while `swingv` attribute is just like an ON/OFF with values from `swing_modes`?

Why not just let us simply merge all the possible `SwingV` modes under `swing_modes` and use `swingv` to see the current one?
I know it can be `SwingH` and that can also have modes, but the vast majority of the devices have only one way to swing... Benefit would be that it would appear in HA's climate card.

Moreover, I'd use a custom swing dict in the config for the users to map friendly swing names to the `SwingV` modes of IrHvac:
```
  supported_swing_modes:
    SwingV:
      - auto: "Automatik"
      - off: "Off"
      - min: "Vertical slow"
      - mid: "Vertical medium"
      - max: "Vertical fast"
    SwingH:
      - min: "Horizontal slow"
      - mid: "Horizontal medium"
      - max: "Horizontal fast"
```
And present the friendly names towards HA instead of the IrHvac keys. That would be beneficial in multiple aspects:
- various devices could be added with any type of swimgs (not strictly only the ones suggested by HA api)
- these would appear with names preferred by the user
- Vertical and Horrizontal swing options would be all in the same dropdown of the official HA user interface, no need to create `select`s etc.
- language issues could be easily handled

**Comment by nagyrobi** [comment]
Moreover, I'd use a custom swing dict in the config for the users to map friendly swing names to both `SwingV` and `SwingH` modes of IrHvac:
```
  supported_swing_modes:
    SwingV:
      - auto: "Automatik"
      - off: "Off"
      - min: "Vertical slow"
      - mid: "Vertical medium"
      - max: "Vertical fast"
    SwingH:
      - min: "Horizontal slow"
      - mid: "Horizontal medium"
      - max: "Horizontal fast"
```
And present the friendly names towards HA instead of the IrHvac keys. That would be beneficial in multiple aspects:
- various devices could be added with any type of swimgs (not strictly only the ones suggested by HA api)
- these would appear with names preferred by the user
- Vertical and Horrizontal swing options would be all in the same dropdown of the official HA user interface, no need to create `select`s etc.
- language issues could be easily handled

When a user selects an entry from under `SwingV`, the payload will contain `SwingV`. When a user selects an entry from under `SwingH`, the payload will contain `SwingH`.
